### ISSUE TITLE
Adjustable font size

### ISSUE THREAD

**Issue by DaniPhii** [apsun/QuoteLock#6]
It would be good if we can adjust the font size, as so many times the clock overlaps with some elements of the UI.

**Comment by apsun** [comment]
Yeah, the quote length can be pretty annoying at times. However, I don't think a manual setting is a good solution, since the quote length can vary every time you pull a new one. An text view that automatically scales the font size to fit a certain height would be better IMO.

I've tried https://github.com/grantland/android-autofittextview, which kind of works (fits a certain number lines instead of pixel height). However, for longer quotes it makes the text so small that it's basically unreadable. I'll have to think about this some more.

**Comment by DaniPhii** [comment]
You're right, it'd become useless if we can't read the quote. What about setting a minimum readable font size just as you suggest and, in addition, some way of making it fold out? I mean, first we can see a preview and if we touch it, it folds out. Or maybe fixing the clock position and diminishing space for notifications can be another valid option. I'm not sure, though.

**Comment by apsun** [comment]
The preview idea sounds interesting! I'll look into it, thanks.

**Comment by shubhendrasingh2808** [comment]
Automatic font adjustment is good but till then, manual font adjustment would be good. Having it is always better than not having it.

**Comment by apsun** [comment]
Added manual font settings in 69d984e7c0b41b933c7df326762a09f3cb8270d5 (v1.3.0). Auto-sizing remains really hard, so I think I'll leave it as a manual thing for now.
